### ISSUE TITLE
Flush the Operations-History periodically 

### ISSUE THREAD

**Issue by kingkrausel** [rwth-acis/Yatta#4]
The operation-history is transmitted to all late-join-users. But the history gets quite fast, really huge in some applications, like collaborative drawing apps. This also causes crashes.

This issue could be handled If a history-flush method would be provided.

**Comment by DadaMonad** [comment]
I decided not to implement this feature.

The syncing process is quite expensive. You have to perform a handshave with _every_ connected user, and, therefore, the process is very expensive if you are in a session with a large number of users.

I close this issue and suggest that an application should not use the Yatta for storing objects only a few milliseconds.
